# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f19bfdc8f164cd1a44c5d8e1cf7d189f36dfeb114867a99ce97009a80ff4a17db37737c610ce4a7ab022e1a4a704c146ea12da99ee0adaf536d042998f4758a6

test:
  secret_key_base: 869cb8f927a692102dba40171053a6d18ec0283b200ceb70812a318d218afa04a81e146504497c5c6074809ac4fcf850d88ac83ccdc63c06fe7eda039d46b9c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
